import { AlertTriangle, ArrowLeft, CheckCircle2, Clock3, Smartphone, X } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Header } from '../components/Header'
import { PrivacyTimeout } from '../components/PrivacyTimeout'
import { useApp } from '../context/AppContext'

export function EmergencyPage() {
  const [confirm, setConfirm] = useState(false)
  const { patient, waitingEstimate, insertEmergency } = useApp()
  const navigate = useNavigate()
  return <div className="terminal-shell"><Header title="急诊优先流程演示" subtitle="工作人员二次确认 · 患者端隐私保护" /><PrivacyTimeout /><main className="grid flex-1 place-items-center p-6"><section className="grid w-full max-w-6xl gap-5 lg:grid-cols-[0.85fr_1.15fr]"><div className="rounded-[30px] bg-slate-900 p-8 text-white"><span className="grid h-20 w-20 place-items-center rounded-3xl bg-amber-400 text-slate-950"><AlertTriangle size={42} /></span><p className="mt-7 text-sm font-black tracking-widest text-amber-300">EMERGENCY PRIORITY DEMO</p><h1 className="mt-3 text-4xl font-black">急诊优先只显示顺序调整，不公开患者病情</h1><p className="mt-4 text-lg font-semibold leading-8 text-slate-300">终端与手机端统一通知：“因急诊患者需优先完成影像检查，当前候检顺序已调整。”</p></div><div className="panel flex flex-col justify-center p-8"><p className="eyebrow">等待时间重新计算</p><div className="mt-5 grid grid-cols-2 gap-4"><div className="rounded-2xl bg-slate-50 p-5"><p className="font-black text-slate-500">原预计</p><p className="mt-2 text-4xl font-black text-slate-900">{patient.previousWaitRange ?? `${waitingEstimate.min}–${waitingEstimate.max}分钟`}</p></div><div className={`rounded-2xl p-5 ${patient.urgentAdjusted ? 'bg-amber-50' : 'bg-blue-50'}`}><p className="font-black text-slate-500">调整后</p><p className={`mt-2 text-4xl font-black ${patient.urgentAdjusted ? 'text-amber-800' : 'text-blue-700'}`}>{patient.urgentAdjusted ? `${waitingEstimate.min}–${waitingEstimate.max}分钟` : '待确认'}</p></div></div>{patient.urgentAdjusted ? <div className="mt-6 space-y-3"><div className="flex items-center gap-3 rounded-2xl bg-emerald-50 p-4 font-black text-emerald-800"><CheckCircle2 />终端候检时间已更新</div><div className="flex items-center gap-3 rounded-2xl bg-sky-50 p-4 font-black text-sky-800"><Smartphone />影途无忧手机端通知已同步</div><button className="primary-action mt-3 w-full" onClick={() => navigate('/waiting')}><ArrowLeft />返回等待状态</button></div> : <button className="primary-action mt-7 w-full" onClick={() => setConfirm(true)}><Clock3 />模拟急诊患者插入</button>}</div></section></main>{confirm && <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal-card text-left"><div className="flex justify-between"><div><p className="eyebrow">工作人员二次确认</p><h2 className="mt-2 text-2xl font-black">确认插入急诊优先流程？</h2></div><button className="header-icon-button" onClick={() => setConfirm(false)}><X /></button></div><p className="mt-5 text-lg font-semibold leading-8 text-slate-600">确认后将重新计算当前患者 ETA，并发送不含急诊患者病情的统一通知。</p><div className="mt-7 grid grid-cols-2 gap-3"><button className="secondary-action" onClick={() => setConfirm(false)}>取消</button><button className="primary-action" onClick={() => { insertEmergency(); setConfirm(false) }}>确认并同步</button></div></div></div>}</div>
}
