import { AlertTriangle, BellRing, CheckCircle2, Clock3, DoorOpen, Gauge, History, LogOut, Megaphone, Pause, Play, RotateCcw, Settings2, ShieldAlert, SlidersHorizontal, Speaker, Square, UserRoundCheck, UsersRound, Volume2, VolumeX, Wrench, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { callAnnouncement, createAnnouncement, customAnnouncement, delayAnnouncement, emergencyAnnouncement, faultAnnouncement, quietAnnouncement, recoveryAnnouncement } from '../services/announcementService'
import { useApp } from '../context/AppContext'
import type { ExamRoomStatus, QueuePatient } from '../types'

type Dialog = 'call' | 'emergency' | 'quiet' | 'special' | 'pause' | 'recovery' | null
const roomMeta: Record<ExamRoomStatus, { label: string; style: string }> = {
  NORMAL: { label: '正常运行', style: 'bg-emerald-50 text-emerald-700' }, MAINTENANCE: { label: '临时维护', style: 'bg-amber-50 text-amber-800' }, DEVICE_FAULT: { label: '临时故障', style: 'bg-amber-50 text-amber-800' }, PAUSED: { label: '暂停检查', style: 'bg-slate-100 text-slate-700' },
}

export function TechnicianDashboard() {
  const navigate = useNavigate()
  const app = useApp()
  const [now, setNow] = useState(new Date())
  const [dialog, setDialog] = useState<Dialog>(null)
  const [emergencyDelay, setEmergencyDelay] = useState(10)
  const [informed, setInformed] = useState(false)
  const [eventType, setEventType] = useState('DEVICE_FAULT')
  const [eventDelay, setEventDelay] = useState<number | undefined>(20)
  const [customText, setCustomText] = useState('')
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(timer) }, [])
  const roomStatus = roomMeta[app.examRoom.status]
  const current = app.queue.find((item) => item.id === app.examRoom.currentPatientId)
  const called = app.queue.find((item) => item.status === 'CALLED')
  const next = app.nextCallable
  const elapsed = Math.max(0, Math.floor((now.getTime() - new Date(app.examRoom.examiningStartedAt).getTime()) / 1000))
  const estimatedMax = app.queue.filter((item) => !['COMPLETED', 'EXAMINING'].includes(item.status)).length * 5 + app.examRoom.etaAdjustment + (app.examRoom.eventDelayMinutes ?? 0)

  const doCall = () => { const patient = app.callNextPatient(next?.id); if (patient) app.publishAnnouncement(callAnnouncement(patient), '叫下一位'); setDialog(null) }
  const repeatCall = () => { const patient = app.repeatCurrentCall(); if (patient) app.publishAnnouncement(callAnnouncement(patient, true), '再次叫号') }
  const confirmEmergency = () => { const eta = app.addEmergencyDelay(emergencyDelay); app.publishAnnouncement(emergencyAnnouncement(emergencyDelay, eta.original, eta.adjusted), '急诊优先', '因急诊优先，您的候检时间已重新计算，请留意最新通知。'); setDialog(null); setInformed(false) }
  const confirmSpecial = () => {
    if (eventType === 'DEVICE_FAULT') { app.setDeviceFault(eventDelay); app.publishAnnouncement(faultAnnouncement(eventDelay), '设备临时故障', '您所在的CT 2号检查室当前设备临时异常，候检顺序已经保留，请留意后续通知。') }
    if (eventType === 'MAINTENANCE') { app.setDeviceMaintenance(eventDelay); const message = createAnnouncement({ type: 'DEVICE_FAULT', priority: 'HIGH', title: '设备临时维护', screenText: `检查设备正在临时维护，候检顺序将保留。${eventDelay ? `预计可能延迟约${eventDelay}分钟。` : '恢复时间正在评估。'}`, ttsText: `各位患者您好，本检查室设备正在临时维护，候检顺序将保留。${eventDelay ? `预计可能延迟约${eventDelay}分钟。` : '恢复时间正在评估中。'}请留意后续通知。`, duration: 12000, requireConfirmation: true, affectsQueue: false, affectsETA: true }); app.publishAnnouncement(message, '设备临时维护') }
    if (eventType === 'PAUSED') { app.pauseQueue(); const message = createAnnouncement({ type: 'DELAY', priority: 'MEDIUM', title: '检查室临时暂停', screenText: '当前检查流程暂时暂停，您的候检顺序将保留，请耐心等待。', ttsText: '各位患者您好，当前检查流程暂时暂停，您的候检顺序将保留，请耐心等待并留意后续通知。', duration: 9000, requireConfirmation: true, affectsQueue: false, affectsETA: true }); app.publishAnnouncement(message, '检查室临时暂停') }
    if (eventType === 'DELAY') { app.addProgressDelay(eventDelay ?? 10); app.publishAnnouncement(delayAnnouncement(eventDelay ?? 10), '检查进度延迟', '当前检查进度有所延迟，您的预计等待时间已更新。') }
    if (eventType === 'RECOVERY') { app.recoverDevice(); app.publishAnnouncement(recoveryAnnouncement(), '设备恢复运行', 'CT 2号检查室已恢复检查，请留意最新候检时间。') }
    if (eventType === 'CUSTOM' && customText.trim()) app.publishAnnouncement(customAnnouncement(customText.trim()), '自定义通知')
    setDialog(null)
  }
  const confirmRecovery = () => { if (app.examRoom.status === 'PAUSED') { app.resumeQueue(); const message = createAnnouncement({ type: 'DEVICE_RECOVERY', priority: 'MEDIUM', title: '候检流程已恢复', screenText: '检查将按照更新后的候检顺序继续进行，请留意叫号。', ttsText: '各位患者您好，候检流程已恢复，检查将按照更新后的候检顺序继续进行，请留意叫号信息。', duration: 7000, requireConfirmation: true, affectsQueue: false, affectsETA: true }); app.publishAnnouncement(message, '恢复候检流程') } else { app.recoverDevice(); app.publishAnnouncement(recoveryAnnouncement(), '设备恢复运行', 'CT 2号检查室已恢复检查，请留意最新候检时间。') } setDialog(null) }

  return <div className="min-h-screen bg-slate-100">
    <header className="flex min-h-20 flex-wrap items-center justify-between gap-4 border-b border-blue-100 bg-white px-6 py-3 shadow-sm"><div className="flex items-center gap-4"><span className="logo-mark"><Wrench /></span><div><h1 className="text-2xl font-black">影途无忧｜技师工作台</h1><p className="text-sm font-bold text-slate-500">医学影像检查智能候诊与全流程引导终端</p></div></div><div className="flex items-center gap-3"><span className={`rounded-full px-4 py-2 text-sm font-black ${roomStatus.style}`}>● 设备{roomStatus.label}</span><span className="text-xl font-black tabular-nums">{formatTime(now)}</span><button className="secondary-action" onClick={() => { app.logoutStaff(); navigate('/') }}><LogOut size={19} />退出工作人员模式</button></div></header>
    <main className="mx-auto max-w-[1800px] space-y-5 p-5">
      <section className="panel grid gap-4 p-5 md:grid-cols-3 xl:grid-cols-7"><Status label="检查室" value={app.examRoom.name} icon={DoorOpen} /><Status label="设备状态" value={roomStatus.label} icon={Gauge} tone={app.examRoom.status === 'NORMAL' ? 'green' : 'amber'} /><Status label="当前患者" value={current ? `${current.ticketNo}号 ${current.maskedName}` : '—'} icon={UserRoundCheck} /><Status label="检查状态" value={app.examRoom.status === 'NORMAL' ? '正在检查' : '流程暂缓'} icon={Clock3} /><Status label="当前已检查" value={`${String(Math.floor(elapsed / 60)).padStart(2, '0')}:${String(elapsed % 60).padStart(2, '0')}`} icon={Clock3} /><Status label="下一位" value={next ? `${next.ticketNo}号 ${next.maskedName}` : '待更新'} icon={BellRing} /><Status label="候检与最长等待" value={`${app.queue.length - 1}人 · ${Math.max(5, estimatedMax)}–${Math.max(10, estimatedMax + 5)}分钟`} icon={UsersRound} /></section>
      <div className="grid gap-5 xl:grid-cols-[1.12fr_0.88fr]">
        <section className="space-y-5"><div className="grid gap-4 lg:grid-cols-2"><PatientCard title="当前检查患者" patient={current} primary /><PatientCard title="下一位患者" patient={next} onRemind={next && !next.prepared ? () => app.remindPreparation(next.id) : undefined} /></div><QueuePanel queue={app.queue} onMissed={app.markQueueMissed} onRestore={app.restoreQueuePatient} onRemind={app.remindPreparation} /></section>
        <section className="space-y-5"><div className="panel p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">QUICK ACTIONS</p><h2 className="mt-1 text-2xl font-black">快速操作中心</h2></div><Megaphone className="text-blue-600" /></div><div className="mt-5 grid grid-cols-2 gap-3"><Quick icon={BellRing} label="叫下一位" primary onClick={() => setDialog('call')} disabled={!next || app.examRoom.callPaused || app.examRoom.status !== 'NORMAL'} /><Quick icon={Volume2} label="再次叫号" onClick={repeatCall} disabled={!called} /><Quick icon={ShieldAlert} label="急诊优先" tone="amber" onClick={() => setDialog('emergency')} /><Quick icon={VolumeX} label="安静提醒" tone="sky" onClick={() => setDialog('quiet')} /><Quick icon={Wrench} label="特殊事件" tone="amber" onClick={() => setDialog('special')} /><Quick icon={app.examRoom.callPaused ? Play : Pause} label={app.examRoom.callPaused ? '恢复候检' : '暂停叫号'} onClick={() => app.examRoom.callPaused ? setDialog('recovery') : setDialog('pause')} /></div></div><EtaAndAudio /><DemoScenarios onScenario={(value) => { if (value === 'call') setDialog('call'); if (value === 'emergency') { setEmergencyDelay(10); setDialog('emergency') } if (value === 'fault') { setEventType('DEVICE_FAULT'); setEventDelay(20); setDialog('special') } if (value === 'recovery') setDialog('recovery') }} /></section>
      </div>
      <div className="grid gap-5 xl:grid-cols-[0.7fr_1.3fr]"><BroadcastStatus /><AnnouncementHistory /></div>
    </main>
    {dialog === 'call' && <SimpleDialog title="叫下一位" onClose={() => setDialog(null)} footer={<><button className="secondary-action" onClick={() => setDialog(null)}>取消</button><button className="primary-action" onClick={doCall}>确认叫号</button></>}><Preview title="即将呼叫" screen={`${next?.ticketNo ?? '--'}号 ${next?.maskedName ?? ''}\n前往：CT 2号检查室`} tts={next ? callAnnouncement(next).ttsText : ''} /></SimpleDialog>}
    {dialog === 'quiet' && <SimpleDialog title="温馨提醒" onClose={() => setDialog(null)} footer={<><button className="secondary-action" onClick={() => setDialog(null)}>取消</button><button className="primary-action" onClick={() => { app.publishAnnouncement(quietAnnouncement(), '安静提醒'); setDialog(null) }}>播放</button></>}><Preview screen="🔇 温馨提醒\n请降低交谈音量，共同保持安静舒适的候检环境" tts={quietAnnouncement().ttsText} /></SimpleDialog>}
    {dialog === 'emergency' && <SimpleDialog title="急诊优先确认" onClose={() => setDialog(null)} wide footer={<><button className="secondary-action" onClick={() => setDialog(null)}>取消</button><button className="primary-action" disabled={!informed} onClick={confirmEmergency}>确认并播报</button></>}><label className="flex items-center gap-3 rounded-2xl bg-amber-50 p-4 font-black text-amber-950"><input className="h-6 w-6" type="checkbox" checked={informed} onChange={(e) => setInformed(e.target.checked)} />已口头告知现场候检患者（必选）</label><OptionRow label="急诊检查预计占用时间" values={[5,10,15,20]} value={emergencyDelay} onChange={setEmergencyDelay} /><Preview screen={`急诊患者优先检查\n候检顺序已调整，预计等待时间可能延长约${emergencyDelay}分钟。`} tts={emergencyAnnouncement(emergencyDelay, '', '').ttsText} /></SimpleDialog>}
    {dialog === 'special' && <SimpleDialog title="特殊事件通知中心" onClose={() => setDialog(null)} wide footer={<><button className="secondary-action" onClick={() => setDialog(null)}>取消</button><button className="primary-action" disabled={eventType === 'CUSTOM' && !customText.trim()} onClick={confirmSpecial}>确认并播报</button></>}><div className="grid grid-cols-2 gap-2 sm:grid-cols-6">{[['DEVICE_FAULT','设备临时故障'],['MAINTENANCE','设备临时维护'],['PAUSED','检查室暂停'],['DELAY','进度延迟'],['RECOVERY','设备恢复运行'],['CUSTOM','自定义通知']].map(([value,label]) => <button key={value} className={`rounded-xl p-3 text-sm font-black ${eventType === value ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-600'}`} onClick={() => setEventType(value)}>{label}</button>)}</div>{eventType !== 'CUSTOM' && eventType !== 'PAUSED' && eventType !== 'RECOVERY' && <><OptionRow label={eventType === 'DEVICE_FAULT' || eventType === 'MAINTENANCE' ? '预计恢复/延迟时间' : '预计延迟'} values={eventType === 'DELAY' ? [5,10,15] : [10,20,30]} value={eventDelay} onChange={setEventDelay} /><button className={`mt-2 rounded-xl px-4 py-2 text-sm font-black ${eventDelay === undefined ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-600'}`} onClick={() => setEventDelay(undefined)}>恢复时间暂不确定</button></>}{eventType === 'CUSTOM' && <label className="mt-4 block font-black">自定义通知（最多100字）<textarea maxLength={100} className="mt-2 min-h-28 w-full rounded-2xl border border-blue-100 bg-slate-50 p-4 font-semibold outline-none" value={customText} onChange={(e) => setCustomText(e.target.value)} /><span className="text-sm text-slate-400">{customText.length}/100</span></label>}<Preview screen={specialPreview(eventType, eventDelay, customText).screen} tts={specialPreview(eventType, eventDelay, customText).tts} /></SimpleDialog>}
    {dialog === 'pause' && <SimpleDialog title="确认暂停候检流程？" onClose={() => setDialog(null)} footer={<><button className="secondary-action" onClick={() => setDialog(null)}>取消</button><button className="primary-action" onClick={() => { app.pauseQueue(); setDialog(null) }}>确认暂停</button></>}><p className="text-lg font-semibold leading-8 text-slate-600">暂停后自动叫下一位将停用，现有患者不会从队列中删除，ETA 将显示受流程状态影响。</p></SimpleDialog>}
    {dialog === 'recovery' && <SimpleDialog title={app.examRoom.status === 'PAUSED' ? '确认恢复候检流程？' : '设备已恢复正常？'} onClose={() => setDialog(null)} footer={<><button className="secondary-action" onClick={() => setDialog(null)}>取消</button><button className="primary-action" onClick={confirmRecovery}>确认恢复并播报</button></>}><Preview screen={app.examRoom.status === 'PAUSED' ? '✓ 候检流程已恢复\n检查将按照更新后的候检顺序继续进行。' : '✓ 设备已恢复运行\n检查将按照更新后的候检顺序继续进行。'} tts={app.examRoom.status === 'PAUSED' ? '各位患者您好，候检流程已恢复，检查将按照更新后的候检顺序继续进行，请留意叫号信息。' : recoveryAnnouncement().ttsText} /></SimpleDialog>}
  </div>
}

function Status({ label, value, icon: Icon, tone = 'blue' }: { label: string; value: string; icon: typeof Clock3; tone?: 'blue'|'green'|'amber' }) { return <div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${tone === 'green' ? 'bg-emerald-100 text-emerald-700' : tone === 'amber' ? 'bg-amber-100 text-amber-700' : 'bg-blue-100 text-blue-700'}`}><Icon size={22} /></span><div className="min-w-0"><p className="text-xs font-black text-slate-400">{label}</p><p className="mt-1 truncate font-black">{value}</p></div></div> }
function PatientCard({ title, patient, primary, onRemind }: { title: string; patient?: QueuePatient; primary?: boolean; onRemind?: () => void }) { return <article className={`rounded-[26px] p-5 ${primary ? 'bg-gradient-to-br from-blue-700 to-cyan-500 text-white' : 'panel'}`}><p className={`text-xs font-black tracking-widest ${primary ? 'text-blue-100' : 'text-blue-600'}`}>{title}</p><div className="mt-4 flex items-end justify-between"><div><p className="text-3xl font-black">{patient ? `${patient.ticketNo}号 ${patient.maskedName}` : '暂无'}</p><p className={`mt-2 font-bold ${primary ? 'text-blue-100' : 'text-slate-500'}`}>{patient?.examName ?? '等待队列更新'}</p></div>{patient && <span className={`rounded-full px-3 py-1 text-sm font-black ${patient.prepared ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-900'}`}>{patient.prepared ? '已准备' : '准备未完成'}</span>}</div>{patient && !primary && <div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs font-black"><span className="rounded-xl bg-emerald-50 p-2 text-emerald-700">{patient.prepared ? '✓' : '○'} 检查准备</span><span className="rounded-xl bg-sky-50 p-2 text-sky-700">{patient.positionTrainingCompleted ? '✓' : '○'} 体位学习</span><span className="rounded-xl bg-slate-100 p-2 text-slate-600">○ 等待叫号</span></div>}{onRemind && <button className="secondary-action mt-3 w-full" onClick={onRemind}><BellRing size={18} />提醒准备</button>}</article> }
function QueuePanel({ queue, onMissed, onRestore, onRemind }: { queue: QueuePatient[]; onMissed: (id: string) => void; onRestore: (id: string) => void; onRemind: (id: string) => void }) { return <section className="panel p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">SHARED QUEUE</p><h2 className="mt-1 text-2xl font-black">候检队列</h2></div><span className="rounded-full bg-emerald-50 px-3 py-2 text-sm font-black text-emerald-700">患者端实时同步</span></div><div className="mt-4 space-y-2">{queue.map((patient) => <div key={patient.id} className="grid items-center gap-3 rounded-2xl bg-slate-50 p-3 sm:grid-cols-[60px_1fr_auto]"><span className="text-center text-xl font-black text-blue-700">{patient.ticketNo}</span><div><p className="font-black">{patient.maskedName} <span className="ml-2 text-sm text-slate-500">{queueLabel(patient)}</span></p><p className="mt-1 text-xs font-bold text-slate-500">准备 {patient.prepared ? '✓' : '○'} · 体位学习 {patient.positionTrainingCompleted ? '✓' : '○'} {patient.staffReviewRequired && <span className="ml-2 text-amber-700">⚠ 有安全事项待工作人员确认</span>}</p></div><div className="flex gap-2">{!patient.prepared && <button className="rounded-xl bg-blue-50 px-3 py-2 text-xs font-black text-blue-700" onClick={() => onRemind(patient.id)}>提醒准备</button>}{patient.status === 'CALLED' && <button className="rounded-xl bg-amber-50 px-3 py-2 text-xs font-black text-amber-800" onClick={() => onMissed(patient.id)}>暂缓</button>}{patient.status === 'MISSED' && <button className="rounded-xl bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-700" onClick={() => onRestore(patient.id)}>恢复候检</button>}</div></div>)}</div></section> }
function Quick({ icon: Icon, label, onClick, primary, tone, disabled }: { icon: typeof BellRing; label: string; onClick: () => void; primary?: boolean; tone?: string; disabled?: boolean }) { return <button disabled={disabled} onClick={onClick} className={`flex min-h-24 flex-col items-start justify-between rounded-2xl p-4 text-left font-black transition disabled:opacity-40 ${primary ? 'bg-gradient-to-br from-blue-700 to-cyan-500 text-white shadow-lg' : tone === 'amber' ? 'bg-amber-50 text-amber-900' : tone === 'sky' ? 'bg-sky-50 text-sky-900' : 'bg-slate-100 text-slate-800'}`}><Icon size={27} /><span>{label}</span></button> }
function EtaAndAudio() { const app = useApp(); return <div className="panel p-5"><div className="flex items-center gap-2"><SlidersHorizontal className="text-blue-600" /><h2 className="text-xl font-black">ETA 与音频设置</h2></div><p className="mt-4 text-sm font-black text-slate-500">预计时间人工修正</p><div className="mt-2 grid grid-cols-4 gap-2">{[-5,5,10,0].map((value) => <button key={value} onClick={() => app.setEtaAdjustment(value)} className={`rounded-xl p-2 text-sm font-black ${app.examRoom.etaAdjustment === value ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-600'}`}>{value === 0 ? '恢复预测' : `${value > 0 ? '+' : ''}${value}分钟`}</button>)}</div><div className="mt-5 flex items-center gap-3"><button className="header-icon-button" onClick={app.toggleAudioMuted}>{app.audioMuted ? <VolumeX /> : <Volume2 />}</button><input aria-label="语音播报音量" className="flex-1" type="range" min="0" max="100" value={app.audioVolume} onChange={(e) => app.setAudioVolume(Number(e.target.value))} /><span className="w-12 text-right font-black">{app.audioVolume}</span></div><div className="mt-3 flex gap-2"><select value={app.autoQuietMinutes} onChange={(e) => app.setAutoQuietMinutes(Number(e.target.value) as 0|30|60)} className="min-h-11 flex-1 rounded-xl bg-slate-100 px-3 text-sm font-black"><option value="0">自动安静提醒：关闭</option><option value="30">每30分钟</option><option value="60">每60分钟</option></select><button className="secondary-action min-h-11" onClick={() => app.publishAnnouncement(createAnnouncement({ type: 'QUIET', priority: 'LOW', title: '语音测试', screenText: '语音播报测试', ttsText: '影途无忧语音播报测试。', duration: 4000, requireConfirmation: false, affectsQueue: false, affectsETA: false }), '音频测试')}>测试播报</button></div></div> }
function DemoScenarios({ onScenario }: { onScenario: (scenario: string) => void }) { return <div className="panel p-5"><div className="flex items-center gap-2"><Settings2 className="text-blue-600" /><h2 className="text-xl font-black">演示场景</h2></div><div className="mt-4 grid grid-cols-4 gap-2">{[['call','A 正常叫号'],['emergency','B 急诊插入'],['fault','C 设备故障'],['recovery','D 设备恢复']].map(([value,label]) => <button key={value} className="rounded-xl bg-slate-100 p-3 text-xs font-black text-slate-700" onClick={() => onScenario(value)}>{label}</button>)}</div><p className="mt-3 text-xs font-bold text-slate-400">场景仅预填参数，仍需完成正常确认流程。</p></div> }
function BroadcastStatus() { const app = useApp(); return <section className="panel p-5"><div className="flex items-center gap-2"><Speaker className="text-blue-600" /><h2 className="text-xl font-black">当前广播状态</h2></div>{app.broadcastingAnnouncement ? <div className="mt-4"><p className="font-black">🔊 当前正在播报：{app.broadcastingAnnouncement.title}</p><div className="mt-4 h-3 overflow-hidden rounded-full bg-slate-100"><div className="broadcast-progress h-full rounded-full bg-blue-600" /></div><button className="secondary-action mt-4 w-full" onClick={app.stopBroadcast}><Square size={17} />停止播报</button></div> : <p className="mt-5 rounded-2xl bg-slate-50 p-4 font-bold text-slate-500">当前无语音播报，后续消息将按优先级排队播放。</p>}</section> }
function AnnouncementHistory() { const app = useApp(); return <section className="panel p-5"><div className="flex items-center gap-2"><History className="text-blue-600" /><h2 className="text-xl font-black">最近广播记录</h2></div><div className="mt-4 max-h-64 space-y-2 overflow-y-auto">{app.announcementHistory.length ? app.announcementHistory.map((item) => <div key={item.id} className="grid gap-2 rounded-xl bg-slate-50 p-3 text-sm sm:grid-cols-[64px_1fr_1fr_1fr]"><span className="font-black text-blue-700">{formatTime(new Date(item.time))}</span><span className="font-black">{item.label}</span><span className="font-bold text-slate-500">{item.operator}</span><span className="font-bold text-slate-500">{item.result}</span></div>) : <p className="p-5 text-center font-bold text-slate-400">暂无广播记录</p>}</div></section> }
function SimpleDialog({ title, children, footer, onClose, wide }: { title: string; children: React.ReactNode; footer: React.ReactNode; onClose: () => void; wide?: boolean }) { return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className={`max-h-[90vh] overflow-y-auto rounded-[30px] bg-white p-7 shadow-2xl ${wide ? 'w-full max-w-3xl' : 'w-full max-w-xl'}`}><div className="flex items-start justify-between"><div><p className="eyebrow">工作人员确认</p><h2 className="mt-2 text-2xl font-black">{title}</h2></div><button className="header-icon-button" onClick={onClose}><X /></button></div><div className="mt-5">{children}</div><div className="mt-6 grid grid-cols-2 gap-3">{footer}</div></div></div> }
function Preview({ title = '播报预览', screen, tts }: { title?: string; screen: string; tts: string }) { return <div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs font-black text-blue-600">【屏幕将显示】</p><p className="mt-2 whitespace-pre-line font-black leading-7">{title}\n{screen}</p></div><div className="rounded-2xl bg-slate-900 p-4 text-white"><p className="text-xs font-black text-cyan-300">【语音将播报】</p><p className="mt-2 font-semibold leading-7 text-slate-200">{tts}</p></div></div> }
function OptionRow({ label, values, value, onChange }: { label: string; values: number[]; value?: number; onChange: (value: number) => void }) { return <div className="mt-4"><p className="text-sm font-black text-slate-500">{label}</p><div className="mt-2 grid grid-cols-4 gap-2">{values.map((item) => <button key={item} className={`rounded-xl p-3 font-black ${value === item ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-600'}`} onClick={() => onChange(item)}>{item}分钟</button>)}</div></div> }
function queueLabel(patient: QueuePatient) { const label: Record<string,string> = { EXAMINING:'正在检查', NEXT:'下一位', READY:'已准备', WAITING:'候检', TEMP_LEAVE:'暂离', CALLED:'已叫号', MISSED:'暂缓', COMPLETED:'已完成', URGENT_DELAY:'因急诊调整' }; return label[patient.status] ?? patient.status }
function specialPreview(type: string, delay?: number, custom = '') { if (type === 'CUSTOM') return { screen: custom || '请输入通知内容', tts: custom || '输入后生成语音预览' }; if (type === 'RECOVERY') { const a = recoveryAnnouncement(); return { screen: a.screenText, tts: a.ttsText } } if (type === 'DELAY') { const a = delayAnnouncement(delay ?? 10); return { screen: a.screenText, tts: a.ttsText } } if (type === 'PAUSED') return { screen: '当前检查流程暂时暂停，候检顺序将保留。', tts: '各位患者您好，当前检查流程暂时暂停，请耐心等待并留意后续通知。' }; const a = faultAnnouncement(delay); return { screen: type === 'MAINTENANCE' ? a.screenText.replace('临时异常','临时维护') : a.screenText, tts: type === 'MAINTENANCE' ? a.ttsText.replace('临时异常','临时维护') : a.ttsText } }
function formatTime(date: Date) { return new Intl.DateTimeFormat('zh-CN', { hour: '2-digit', minute: '2-digit', hour12: false }).format(date) }
